site_name: Inventory Profiles Next
site_description: An inventory sorter mod

theme:
  name: material
  custom_dir: overrides

  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep orange
      accent: deep orange
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep orange
      accent: deep orange
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

  icon:
    repo: fontawesome/brands/github

  features:
    - navigation.sections
    - navigation.instant

markdown_extensions:
  - footnotes
  - attr_list
  - pymdownx.tabbed
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons

plugins:
  - search
  - i18n:
      default_language: en
      languages:
        en: English
        eo: Esperanto
        fr: Français
      nav_translations:
        fr:
          Custom rules: Règles personnalisées
          Project details: Détails du projet
        eo:
          Custom rules: Propraj reguloj
          Project details: Informoj de projekto
  - minify:
      minify_html: true

repo_url: https://github.com/blackd/Inventory-Profiles
repo_name: Inventory-Profiles

edit_uri: https://github.com/Inventory-Profiles-Next/Inventory-Profiles-Next.github.io/edit/main/docs/

nav:
  - Inventory Profiles Next:
    - index.md
    - downloads/index.md
    - installation/index.md
    # - profiles.md
    - Custom rules:
      - custom-rules/add/index.md
      - custom-rules/natives/index.md
  
  - Project details:
    - changelog/index.md
    - known-issues/index.md
    - contributing/index.md
    - thanks/index.md
    - license/index.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Inventory-Profiles-Next
    - icon: fontawesome/brands/discord
      link: https://discord.gg/23YCxmveUM
    - icon: custom/curseforge
      link: https://www.curseforge.com/minecraft/mc-mods/inventory-profiles-next
    - icon: custom/modrinth
      link: https://modrinth.com/mod/inventory-profiles-next

extra_css:
  - stylesheets/extra.css
