site_name: Inventory Profiles Next

theme:
  name: material

  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep orange
      accent: deep orange
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep orange
      accent: deep orange
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

  icon:
    repo: fontawesome/brands/github

  features:
    - navigation.sections
    - navigation.instant

markdown_extensions:
  - pymdownx.tabbed

plugins:
  - i18n:
      default_language: en
      languages:
        en: english
        eo: Esperanto
        fr: français
      nav_translations:
        fr:
          Custom rules: Règles personnalisées
          Project details: Détails du projet
        eo:
          Custom rules: Propraj reguloj
          Project details: Informoj de projekto
  - minify:
      minify_html: true

repo_url: https://github.com/blackd/Inventory-Profiles
repo_name: Inventory-Profiles

edit_uri: https://github.com/Inventory-Profiles-Next/Inventory-Profiles-Next.github.io/edit/main/docs/

nav:
  - Inventory Profiles Next:
    - index.md
    - downloads.md
    - installation.md
    # - profiles.md
    - Custom rules:
      - custom-rules/add.md
      - custom-rules/natives.md
  
  - Project details:
    - changelog.md
    - known-issues.md
    - contributing.md
    - thanks.md
    - license.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Inventory-Profiles-Next
    - icon: fontawesome/brands/discord
      link: https://discord.gg/23YCxmveUM
    - icon: fontawesome/solid/fire
      link: https://www.curseforge.com/minecraft/mc-mods/inventory-profiles-next
    - icon: fontawesome/solid/wrench
      link: https://modrinth.com/mod/inventory-profiles-next

  alternate:
    - name: English
      lang: en
      link: ./
    - name: Esperanto
      lang: eo
      link: ./eo/
    - name: Français
      lang: fr
      link: ./fr/

extra_css:
  - stylesheets/extra.css
